{"name": "创建英雄_test_create_hero_volume_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'name': 'volume_fail', 'power': 20, 'volume': 1} == False", "trace": "self = <test_game_by_data.test_create_hero.Test_hero object at 0x0000015A4A8A4AD0>\nget_hero_volume_fail = 1\n\n    @allure.title(\"创建英雄_test_create_hero_volume_fail\")\n    @pytest.mark.FAIL\n    @pytest.mark.run(order=1)\n    # @pytest.mark.parametrize(\"volume\", LoadUtils.loadData(\"test_hero_create.yaml\")[\"volume_fail\"], ids=[\"血量_fail_0\", \"血量_fail_100\", \"血量_fail_-1\"])\n    def test_create_hero_volume_fail(self, get_hero_volume_fail):\n        hero_management = HeroManagement()\n        hero_management.create_hero(\"volume_fail\", get_hero_volume_fail, 20)\n        res = hero_management.find_hero(\"volume_fail\")\n>       assert res == False\nE       AssertionError: assert {'name': 'volume_fail', 'power': 20, 'volume': 1} == False\n\ntest_create_hero.py:48: AssertionError"}, "attachments": [{"name": "stdout", "source": "00070520-b38a-4e13-a252-80f2117b5a66-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_hero_volume_fail", "value": "0"}], "start": 1684677423576, "stop": 1684677423576, "uuid": "1af3659b-3dfc-4c89-a29d-ec53a72b4356", "historyId": "40a91321ae292c71a0a4ebd68deaec0b", "testCaseId": "f5f61fc604dfcfc05c708aa91157d267", "fullName": "test_create_hero.Test_hero#test_create_hero_volume_fail", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "FAIL"}, {"name": "suite", "value": "test_create_hero"}, {"name": "subSuite", "value": "Test_hero"}, {"name": "host", "value": "WIN-20230414OLX"}, {"name": "thread", "value": "14340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_hero"}]}